### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by whes1015** [TasosY2K/ESP8266-Phising#1]
Errors are always displayed ERR_TOO_MANY_REDIRECTS

When connecting to a network, you always direct to the URL below
http://www.msftconnecttest.com/redirect

**Comment by TasosY2K** [comment]
You're providing me too little info, but if i had to guess this sounds like an issue with your board. Try flashing on a new one.

**Comment by dekronite** [comment]
im also getting the same thing im pretty sure its something to do with the http and https requests, the request happens whenever i try to connect, i have tried from multiple devices and nothing just the error message.
